apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/calungaproject/npm-registry?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: calunga-npm-registry-main
    appstudio.openshift.io/component: calunga-npm-registry-main
    pipelines.appstudio.openshift.io/type: build
  name: calunga-npm-registry-main-on-pull-request
  namespace: calunga-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/calunga-tenant/calunga-npm-registry-main:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: prev-packages-ref
      value: 'origin/{{target_branch}}'
    - name: git-clone-depth
      value: "0"
    - name: builder-image
      value: quay.io/redhat-user-workloads/calunga-tenant/npm-builder@sha256:7e067c1f6a0bf8a7d9b3f07e6e6b517ce49932362ca1b433a8e505ab22be680a
    - name: task-build-npm-package-bundle
      value: quay.io/redhat-user-workloads/calunga-tenant/task-build-npm-package@sha256:07eb8f459845a630325fe8620f565ac31072d06de844ce8819cf033c4c872bf1
  taskRunTemplate:
    serviceAccountName: build-pipeline-calunga-npm-registry-main
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
  pipelineRef:
    name: build-npm
  taskRunSpecs:
    - pipelineTaskName: build-npm-package
      computeResources:
        requests:
          memory: 8Gi
        limits:
          memory: 12Gi
status: {}
